name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - gdal
  - pip:
    - gdal
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
